// src/game/maps.js
// Mapas de la Región Satélite — formato: 1 carácter = 1 tile
//  T árbol      . césped      , flores     G hierba alta   p camino
//  w agua       s arena       R techo rojo C techo centro  B techo azul (lab)
//  W pared      D puerta      S cartel     = valla         i objeto
//  (bloquean: T w R C B W S = ; D se maneja como acción especial)

export const SOLID_TILES = new Set(['T', 'w', 'R', 'C', 'B', 'W', 'S', '=']);

export const MAPS = {
    pueblo: {
        name: 'Pueblo Órbita',
        zoneTypes: null, // sin encuentros
        levelRange: null,
        grid: [
            'TTTTTTTTppTTTTTTTTTT',
            'T,,.....pp.........T',
            'T..RRR..pp..RRR....T',
            'T..WDW..pp..WDW....T',
            'T.......pp.........T',
            'T..BBBB.pp....=====T',
            'T..WWDW.pp...,,,,,.T',
            'T.......pp...,,,,,.T',
            'T..ppppppppppppp...T',
            'T..p...........p...T',
            'T..p...,,,.....p.i.T',
            'T..p...,,,.....p...T',
            'T..ppppppppppppp...T',
            'T,,................T',
            'TTTTTTTTTTTTTTTTTTTT',
        ],
        actions: {
            '8,0':  { type: 'warp', to: 'ruta1', x: 8, y: 22 },
            '9,0':  { type: 'warp', to: 'ruta1', x: 9, y: 22 },
            '5,6':  { type: 'lab' },
            '4,3':  { type: 'msg', text: 'Es tu casa. ¡Tu aventura te espera fuera!' },
            '13,3': { type: 'msg', text: 'La puerta está cerrada.' },
        },
        spawn: { x: 9, y: 9, dir: 'down' },
    },

    ruta1: {
        name: 'Ruta Estelar 1',
        zoneTypes: ['normal', 'grass', 'bug'],
        levelRange: [2, 5],
        grid: [
            'TTTTTTTTTTppTTTTTTTT',
            'T.....GGG.pp.......T',
            'T..GGGGGG.pp..GGG..T',
            'T..GGGG...pp..GGG..T',
            'T.........pp..GGG..T',
            'T..,,.....pp.......T',
            'T..,,..ppppp..i....T',
            'T......p...........T',
            'T..GGG.p..GGGG.....T',
            'T..GGG.p..GGGG.....T',
            'T..GGG.p..GGGG.....T',
            'T......p...........T',
            'T..S...p....,,,....T',
            'T......ppppppp.....T',
            'T............p.....T',
            'T..GGGGG.....p.....T',
            'T..GGGGG.....p..GG.T',
            'T..GGGGG.....p..GG.T',
            'T............p.....T',
            'T....,,......p.....T',
            'T............p.....T',
            'T.......pppppp.....T',
            'T.......pp.........T',
            'TTTTTTTTppTTTTTTTTTT',
        ],
        actions: {
            '10,0': { type: 'warp', to: 'ciudad', x: 11, y: 15 },
            '11,0': { type: 'warp', to: 'ciudad', x: 12, y: 15 },
            '8,22': { type: 'warp', to: 'pueblo', x: 8, y: 1 },
            '9,22': { type: 'warp', to: 'pueblo', x: 9, y: 1 },
            '3,12': { type: 'msg', text: 'RUTA ESTELAR 1 — Pueblo Órbita al sur, Ciudad Cometa al norte.' },
        },
        spawn: { x: 9, y: 21, dir: 'up' },
    },

    ciudad: {
        name: 'Ciudad Cometa',
        zoneTypes: null,
        levelRange: null,
        grid: [
            'TTTTTTTTTTTTTTTTTTTTTTTT',
            'T......................T',
            'T..RRR....RRRR....RRR..T',
            'T..WDW....WWDW....WDW..T',
            'T......................T',
            'T..ppppppppppppppppp...T',
            'T..p......CCCC.....p...T',
            'T..p......WWDW.....p,,.T',
            '...p...............p...T',
            '.ppppppppppppppppppppp..',
            'T..p...............p...T',
            'T..p..RRR...RRR....p...T',
            'T..p..WDW...WDW....p...T',
            'T..p...............p...T',
            'T..ppppppppp...i...p...T',
            'T..........pp......p...T',
            'T..........pp.ppppppp..T',
            'TTTTTTTTTTTppTTTTTTTTTTT',
        ],
        actions: {
            '11,17': { type: 'warp', to: 'ruta1', x: 10, y: 1 },
            '12,17': { type: 'warp', to: 'ruta1', x: 11, y: 1 },
            '0,8':   { type: 'warp', to: 'bosque', x: 20, y: 8 },
            '0,9':   { type: 'warp', to: 'bosque', x: 20, y: 9 },
            '23,9':  { type: 'warp', to: 'ruta2', x: 1, y: 6 },
            '12,7':  { type: 'heal' },
            '4,3':   { type: 'msg', text: 'Hay alguien durmiendo dentro...' },
            '12,3':  { type: 'msg', text: 'TIENDA — Próximamente.' },
            '19,3':  { type: 'msg', text: 'La puerta está cerrada con llave.' },
            '7,12':  { type: 'msg', text: '«¡Los Pokémon del Lago Eclipse son muy fuertes!»' },
            '13,12': { type: 'msg', text: '«El Bosque Lunar esconde Pokémon psíquicos...»' },
        },
        spawn: { x: 12, y: 10, dir: 'down' },
    },

    bosque: {
        name: 'Bosque Lunar',
        zoneTypes: ['bug', 'grass', 'psychic', 'ghost', 'poison'],
        levelRange: [4, 8],
        grid: [
            'TTTTTTTTTTTTTTTTTTTTT',
            'TTT.GGG..TT..GGGG..TT',
            'TT..GGG..TT..GGGG..TT',
            'TT..GGG......GGGG...T',
            'TT.......TT.........T',
            'TT.TTTT..TT..TTTT...T',
            'TT.TGGG..TT..i......T',
            'TT.TGGG..TTTTTTTT...T',
            'TT.TGGG.............p',
            'TT......TTT.........p',
            'TT.GGGG.TTT..GGGG...T',
            'TT.GGGG.TTT..GGGG...T',
            'TT.GGGG.TTT..GGGG...T',
            'TT......TTT.........T',
            'TT.,,......TT...,,..T',
            'TT....GGG..TT.......T',
            'TTT...GGG..TT..i...TT',
            'TTTTTTTTTTTTTTTTTTTTT',
        ],
        actions: {
            '20,8': { type: 'warp', to: 'ciudad', x: 1, y: 8 },
            '20,9': { type: 'warp', to: 'ciudad', x: 1, y: 9 },
        },
        spawn: { x: 19, y: 8, dir: 'left' },
    },

    ruta2: {
        name: 'Ruta Estelar 2',
        zoneTypes: ['electric', 'fighting', 'normal', 'fire', 'rock', 'ground'],
        levelRange: [8, 13],
        grid: [
            'TTTTTTTTTTTTTTTTTTTTTTTTTT',
            'T....GGGG......GGGG......T',
            'T....GGGG......GGGG..,,..T',
            'T....GGGG......GGGG......T',
            'T........................T',
            'T..ppppppppppppppppppp...T',
            'p..p.................p...p',
            'pppp.................pppp.',
            'T.....GGGG...GGGG........T',
            'T.....GGGG...GGGG...i....T',
            'T.....GGGG...GGGG........T',
            'T.,,.....................T',
            'Tsssssssssssssssssssssssss',
            'Twwwwwwwwwwwwwwwwwwwwwwwww',
        ],
        actions: {
            '0,6':  { type: 'warp', to: 'ciudad', x: 22, y: 9 },
            '0,7':  { type: 'warp', to: 'ciudad', x: 22, y: 9 },
            '25,6': { type: 'warp', to: 'lago', x: 1, y: 6 },
            '25,7': { type: 'warp', to: 'lago', x: 1, y: 7 },
        },
        spawn: { x: 1, y: 6, dir: 'right' },
    },

    lago: {
        name: 'Lago Eclipse',
        zoneTypes: ['water', 'ice', 'dragon', 'fairy', 'flying'],
        levelRange: [11, 16],
        grid: [
            'TTTTTTTTTTTTTTTTTTTT',
            'T...GGG.......GGG..T',
            'T...GGG..,,...GGG..T',
            'T..................T',
            'T...ssssssssssss...T',
            'T...swwwwwwwwwws...T',
            'p...swwwwwwwwwws...T',
            'p...swwwwwwwwwws.i.T',
            'T...swwwwwwwwwws...T',
            'T...swwwwwwwwwws...T',
            'T...ssssssssssss...T',
            'T..................T',
            'T..GGGG......GGGG..T',
            'T..GGGG..,,..GGGG..T',
            'T..GGGG......GGGG..T',
            'TTTTTTTTTTTTTTTTTTTT',
        ],
        actions: {
            '0,6': { type: 'warp', to: 'ruta2', x: 24, y: 6 },
            '0,7': { type: 'warp', to: 'ruta2', x: 24, y: 7 },
        },
        spawn: { x: 1, y: 6, dir: 'right' },
    },
};

export const ENCOUNTER_RATE = 0.13; // probabilidad por paso en hierba alta
